### ISSUE TITLE
accessSecretVersion() fails silently 

### ISSUE THREAD

**Issue by 1N50MN14** [googleapis/nodejs-secret-manager#106]
#### Environment details

  - OS: Alpine
  - Node.js version: 12.6.1
  - `@google-cloud/secret-manager` version: 3.0.0

#### Steps to reproduce

Virtually impossible to without the method throwing any errors even after 8 hours trying to do so. It works fine locally (by manually passing sa credentials) otherwise hangs indefinitely when running within a cluster with all scopes and permissions in place. Readiness kicks in and kills all pods.

This issue is not related to #92 as I don't rely on any of those environment variables.

**Comment by 1N50MN14** [comment]
Below is the only code the pod runs, the same code runs fine locally.

```javascript
const 
  {SecretManagerServiceClient} = require('@google-cloud/secret-manager'),
  client = new SecretManagerServiceClient();

(async () =>
{
  const 
    //gcloud secrets list correct shows the key is there
    key = 'myDummyKey',

    //process.env.GCP_PROJECT is available
    name = `projects/${process.env.GCP_PORJECT}/secrets/${key}/versions/latest`,

    //works fine locally, but not in a cluster. cloud-platform scope is enabled. 
    //secret manager viewer/accessor is correctly set on the service account. 
    [latest] = await client.accessSecretVersion({ name });

    //nothing happens here, process hangs.
})()
```

**Comment by bcoe** [comment]
@1N50MN14 what environment are you running your script within, e.g., Google Cloud Functions?

You mention it's not related to #92, are you connecting through a proxy in some other way, or are you connecting directly to the service?

**Comment by 1N50MN14** [comment]
@bcoe GKE cluster, I just finished re-writing the call using the REST API and have finally pinpointed the error:

`getaddrinfo EAI_AGAIN secretmanager.googleapis.com`

It's a DNS issue, which is very strange. Going to submit a support ticket about this one as it's not specific to this library (`accessSecretVersion` should've still thrown an error though)

**Comment by bcoe** [comment]
@1N50MN14 I can raise this issue with the team that manages code generation 👍 this bug would likely occur across 50 or so of our libraries.

**Comment by 1N50MN14** [comment]
@bcoe That'd be great thank you! In the meantime I'll have to continue investigating the DNS issue as  all of my deployments rely on Secret Manager, hopefully it's just a matter of GKE's NodeLocal DNSCache screwing things up.

**Comment by alexander-fenster** [comment]
@1N50MN14 Just to add some information here - it's how our gRPC transport works: if it cannot connect, it will keep trying and won't fail if it cannot connect for whatever reason (will keep retrying for a long time). This approach has its pros and cons, obviously.

Also, totally unrelated, but you have a typo in your code: `GCP_PORJECT` - I hope it does not break anything for you in your testing.

**Comment by bcoe** [comment]
@1N50MN14 I'm going to close this, since I think we've isolated the issue to this retry behavior. I'm sure this will cause a bit of a discussion internally though on how we could have helped you catch this ... maybe a warning message after N retries?

**Comment by 1N50MN14** [comment]
@alexander-fenster Oh I didn't realize that was an intended behavior, thanks for pointing it out (and the code typo, fortunately it was made only here).

@bcoe Absolutely, yes some sort of warning / clue would've surely been very helpful.

Many thanks again @bcoe and @alexander-fenster, stay safe.
