### ISSUE TITLE
Provide a sync API

### ISSUE THREAD

**Issue by Sytten** [googleapis/nodejs-secret-manager#118]
**Is your feature request related to a problem? Please describe.**
When switching an application from using `process.ENV` to GCP secret manager, you basically need to put everything async because no sync api is provided. This is a big change for existing application that might have a config that was not async.

 **Describe the solution you'd like**
Provide a sync API so the migration to secrets manager is easier even if it is less performant.

 **Describe alternatives you've considered**
You stay with environment variables and you run a script before launching your app to retrieve secrets and inject them in environment variables.

**Comment by JustinBeckwith** [comment]
Greetings folks!  I can appreciate how this would solve some problems coming from a fully sync environment (like env vars), but ultimately this just isn't the direction the API is going to go.  This is an API that's making network calls - sync APIs are likely to be a footgun that's going to trip up more folks than it's going to help.  Alternatively - let me throw a few options out there:

## Using an async main
This is the pattern we actually use in all of our samples today.  I believe if you attach a `.then` to a promise, it prevents the process from exiting until the promise is fulfilled:

```js
async function main() {
 // make async calls
}
main(...args).then(console.log).catch(console.error);
```

## Using top level await
Starting in one of the later versions of Node.js 14, you can now use top level await without a flag!

```js
import {SecretManagerServiceClient} from '@google-cloud/secret-manager';
const client = new SecretManagerServiceClient();
const [secret] = await client.getSecret({
  name: 'projects/your-project/secrets/your-secret',
});
const policy = secret.replication.replication;
console.info(`Found secret ${secret.name} (${policy})`);
```

_make sure to set `type: module` in your `package.json` to do this_

## Use a library to makes async calls synchronous
If you really, really need to make these calls synchronous - you can always use a library like deasync:
https://www.npmjs.com/package/deasync

**Comment by micahasmith** [comment]
for when you're really, really stuck--

`npm install -S deasync`

```js
const googleProjectId = process.env.GOOGLE_CLOUD_PROJECT;

const getSecretSync = deasync((name: string, cb:any) => {
  const c = new SecretManagerServiceClient();
  c.getSecret({name: c.secretPath(googleProjectId, name)}).then(([secret]) => {
    // @ts-ignore
      cb(null, secret.payload.data.toString());
  }).catch((err) => {
      cb(err);
  });
});
```
