### ISSUE TITLE
Improve README.md 

### ISSUE THREAD

**Issue by jackton1** [googleapis/nodejs-secret-manager#132]
Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

 **Is your feature request related to a problem? Please describe.**
- Misleading messsage in README.md, since the code isn't executable by just removing the comment.
 
**Describe the solution you'd like**
- Adding a variable definition "const" keyword. 
 
**Describe alternatives you've considered**
- Not Applicable

**Comment by bcoe** [comment]
we should update the `./samples/quickstart.js` to address @jackton1's feedback:

```
// parent = 'projects/my-project', // Project for which to manage secrets.
// secretId = 'foo', // Secret ID.
// payload = 'hello world!' // String source data.
```

to:

```
// const parent = 'projects/my-project', // Project for which to manage secrets.
// const secretId = 'foo', // Secret ID.
// const payload = 'hello world!' // String source data.
```
