### ISSUE TITLE
Property 'replication' does not exist on type 'IReplication'.

### ISSUE THREAD

**Issue by mrdulin** [googleapis/nodejs-secret-manager#150]
#### Environment details

  - OS: macOS 10.13.6 
  - Node.js version: `node -v`, `v12.16.1`
  - npm version: `npm -v`, `6.14.7`
  - `@google-cloud/secret-manager` version: `^3.1.0`
  - `typescript`: `^3.8.3`

#### Steps to reproduce

  1. Follow the [list secrets](https://cloud.google.com/secret-manager/docs/managing-secrets) guide for Node.js
  2. Using TypeScript
  3. When I try to access the `secret.replication.replication` property, TSC throw an error:

> Property 'replication' does not exist on type 'IReplication'.ts(2339)

Code here:
```js
import { SecretManagerServiceClient } from '@google-cloud/secret-manager';
import path from 'path';

const client = new SecretManagerServiceClient({
  keyFile: path.resolve(__dirname, '../../.gcp/secret-manager-admin-svc.json'),
});

async function listSecrets() {
  const parent = 'projects/my-projects';
  const [secrets] = await client.listSecrets({ parent });
  secrets.forEach((secret) => {
    const policy = secret.replication!.replication;
    console.log(`${secret.name} (${policy})`);
  });
}

listSecrets().catch(console.log);
```

```js
/** Properties of a Replication. */
interface IReplication {
  /** Replication automatic */
  automatic?: google.cloud.secretmanager.v1.Replication.IAutomatic | null;

  /** Replication userManaged */
  userManaged?: google.cloud.secretmanager.v1.Replication.IUserManaged | null;
}
```

I don't see `replication` property on the `IReplication` interface.

**Comment by WangHansen** [comment]
Same error? Is there a workaround right now except disable TypeScript?

**Comment by sofisl** [comment]
Hi @mrdulin, this seems like an issue with the sample actually. The type itself only allows for either one of `userManaged` or `automatic` for the policy. The code is a bit clunky, but it should go something like this: 

```
    secrets.forEach(secret => {
      const policy = secret.replication.userManaged
        ? secret.replication.userManaged
        : secret.replication.automatic;
      console.log(`${secret.name} (${policy})`);
    });
```
