### ISSUE TITLE
secret key manager dependency issue

### ISSUE THREAD

**Issue by prasadtechnology** [googleapis/nodejs-secret-manager#151]
Not able to install secret manager dependency, Below is the command i am trying

npm i @google-cloud/secret-manager

log:

npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@google-cloud%2fsecret-manager - Not found
npm ERR! 404 
npm ERR! 404  '@google-cloud/secret-manager@latest' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/prasad/.npm/_logs/2020-08-06T09_28_12_277Z-debug.log

**Comment by prasadtechnology** [comment]
Any updates on this issue please.

**Comment by sofisl** [comment]
Hello @prasadtechnology, we are unable to reproduce the issue. I'm wondering if it might be related to an npm outage. Have you tried rerunning the command since? Thanks in advance.

**Comment by sofisl** [comment]
Here's a link confirming the outage: https://status.npmjs.org/incidents/cksjqc1w11v5. Please feel free to reopen if you still can't access the library.
