### ISSUE TITLE
Access multiple secrets in one request

### ISSUE THREAD

**Issue by elyobo** [googleapis/nodejs-secret-manager#226]
**Is your feature request related to a problem? Please describe.**
When retrieving multiple secrets, multiple calls must be made. While these can all be done in parallel it would be clearer (and presumably involve less overhead) to simply be able to request multiple secrets in one request.

 **Describe the solution you'd like**
Methods that support a single `name` should accept multiple names (not backwards compatible, as the response format would need to change), or new pluralised methods (e.g. `accessSecretVersion` -> `accessSecretVersions`) should be added (backwards compatible) to support retrieval of multiple secrets in one request.

 **Describe alternatives you've considered**

It's possible to achieve most of the benefits of this by requesting multiple secrets in parallel, e.g. pseudcode

```javascript
const [a, b] = Promise.all([client.accessSecretVersion({ name: 'a' }), client.accessSecretVersion({ name: 'b' })])
```

**Comment by sofisl** [comment]
Hi there! I think it would be better to request this directly from [the API](https://issuetracker.google.com/savedsearches/5654226), vs. the client library. Thank you!
