### ISSUE TITLE
GOOGLE_APPLICATION_CREDENTIALS json value, rather than file reference

### ISSUE THREAD

**Issue by barriobuilt** [googleapis/nodejs-secret-manager#235]
It would be handy to assign GOOGLE_APPLICATION_CREDENTIALS a json value, so I can configure this as part of my .env, rather than having to create a json file and reference it. This would simplify my Cloud Run deployment.  It would be even better if I could provide credentials when initializing the SecretManagerServiceClient, so my app could connect with more than one Secrets Manager if necessary.

**Comment by hata6502** [comment]
```js
const client = new SecretManagerServiceClient({
  credentials: {  // Load the credentials directly
    client_email: "XXXXX",
    private_key: "XXXXX",
  }
});

```

**Comment by gregorskii** [comment]
This package also works well with ADC:

https://cloud.google.com/docs/authentication/provide-credentials-adc#local-user-cred

Hope this helps others, I was relying on ENV JSON paths when this works well.
