### ISSUE TITLE
Require http not found when using SvelteKit/vite

### ISSUE THREAD

**Issue by jameslounds** [googleapis/nodejs-secret-manager#309]
When I try to use the node.js secret manager library with Vite, it throws this error
`
 node_modules/vite/dist/node/chunks/dep-85dbaaa7.js:62884:18: note: This error came from the "onResolve" callback registered here
    62884 │             build.onResolve({ filter: /^[\w@][^:]/ }, async ({ path: id, importer, kind }) => {
          ╵      
`
`
./node_modules/tunnel-agent/index.js:5:19: note: The plugin "vite:dep-pre-bundle" was triggered by this import
        5 │   , http = require('http')
`

I can use datastore fine, in the same project, but secret manager isn't happy

#### Environment details

  - OS: MacOS Monterey
  - Node.js version: 14.18.1, (and 16.13.0)
  - npm version: 8.1.0
  - `@google-cloud/secret-manager` version: 3.10.1

#### Steps to reproduce

  1. `git clone https://github.com/cucumberbob123/secret-manager-bug-report.git`
  2. `npm install`
  3. `npm run dev`

Thanks!

**Comment by sofisl** [comment]
Hi @cucumberbob123,

Unfortunately we're not currently set up to support browser-side issues. I'm not familiar with SvelteKit/vite, but from doing a preliminary search online, it looks like this issue might be build related as opposed to library related.

Just to confirm that this is the case, can you confirm one of these samples works for you server-side? https://github.com/googleapis/nodejs-secret-manager/tree/main/samples

Thanks!
