### ISSUE TITLE
Can we access secrets from client app like react app

### ISSUE THREAD

**Issue by navneetgarggate6** [googleapis/nodejs-secret-manager#42]
I want to access secrets/env variables from the client side react app (browser) what is the way to use it ?
do we need to use https://kubernetes.io/docs/reference/using-api/client-libraries/ or we can do it with some other methods where all the keys should secure ?

**Comment by bcoe** [comment]
@navneetgarggate6 while not fully supported, you can potentially use this library in the front-end using the [approach described here](https://github.com/googleapis/google-cloud-node/issues/2933#issuecomment-547657659).

Let us know if you're able to?

**Comment by navneetgarggate6** [comment]
I already checked that implementation but my problem is that i don't want to use auth as i want to access all the secret before login

**Comment by bcoe** [comment]
@navneetgarggate6 I don't believe that there is any way to achieve this, the client library requires authentication before you will be able to access secrets.

What you might want to consider is setting up an endpoint, with a service like express, that your frontend interacts with to access secrets.

Keep in mind, if you don't require authentication, you should be very mindful about exposing secrets on public routes, as anyone in the world will potentially see information critical to your application.

**Comment by lvl99** [comment]
Is it possible to use the secrets manager in conjunction with Firebase Auth?

**Comment by sofisl** [comment]
Hi there! We are migrating this repo to googleapis/google-cloud-node. We kindly ask that you reopen your issue there if you're still experiencing it. Thank you!
