### ISSUE TITLE
PERMISSION_DENIED: Secret Manager API has not been used in project 698910892233

### ISSUE THREAD

**Issue by MartinFreire** [googleapis/nodejs-secret-manager#58]
#### Problem
I tried running a simple test both in my pc and the gcloud online console.

In both I get the same error:
> Error: 7 PERMISSION_DENIED: Secret Manager API has not been used in project 698910892233 before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/secretmanager.googleapis.com/overview?project=698910892233 then retry

My problem is that that project ID is not mine, is not the one in the json key, does not exists on any of the files of my project, or even my pc (even less on the GCloud command line)

#### Env
  - OS: Windows10
  - Node.js version: v10.16.3
  - npm version: 6.9.0
  - `@google-cloud/secret-manager` version: 1.2.1

#### Steps to reproduce
  1.  I tried to run this simple test
```
import { SecretManagerServiceClient } from '@google-cloud/secret-manager';
const client   = new SecretManagerServiceClient();
const [secret] = await client.getSecret({ name: 'latest' });
```

  2. I tried to set the GCloud env settings manually (having saw [this](https://github.com/googleapis/nodejs-secret-manager/issues/20)), but didn't work either
```
import { SecretManagerServiceClient } from '@google-cloud/secret-manager';

process.env.GCP_PROJECT    = 'my-proyect';
process.env.GCLOUD_PROJECT = 'my-proyect'; // '88733305581';
process.env.GOOGLE_APPLICATION_CREDENTIALS = './keys/my-proyect-auth-key.json';

const client   = new SecretManagerServiceClient();
const [secret] = await client.getSecret({ name: 'latest' });
```
I have other GCP products running, like Firestore, Storage and Tasks. They run OK.

But after I follow every step and reach this dead end. I tried searching everywhere I could.
In the meantime I'll solve it in another way. But I would really love to use this

Thanks!

**Comment by bcoe** [comment]
:wave: hey @MartinFreire, so the format should actually be ` projects/my-project`, take a look at the sample:

```js
  // [START secretmanager_create_secret]
  /**
   * TODO(developer): Uncomment these variables before running the sample.
   */
  // const parent = 'projects/my-project';
  // const secretId = 'my-secret';

  // Imports the Secret Manager library
  const {SecretManagerServiceClient} = require('@google-cloud/secret-manager');

  // Instantiates a client
  const client = new SecretManagerServiceClient();

  async function createSecret() {
    const [secret] = await client.createSecret({
      parent: parent,
      secretId: secretId,
      secret: {
        replication: {
          automatic: {},
        },
      },
    });
```

I think this is probably what was biting you :ok_hand:  let me know if adding the `projects` prefix helps.

**Comment by MartinFreire** [comment]
Hi, I created the secret on the web interface, I'm just trying to read it not creating it.
Can I change that parameter on the Web UI?
Thanks!

**Comment by bcoe** [comment]
@MartinFreire here's some example code I use:

https://github.com/googleapis/repo-automation-bots/blob/master/packages/publish/src/publish.ts#L143

Note that the method `accessSecretVersion` is used, and that it requires the full path to the secret, including `projects/project` (in the sample code I'm grabbing the latest version of the secret).

**Comment by MartinFreire** [comment]
Ok your snippet works excellent, thanks!
I searched for a read example on here
https://github.com/googleapis/google-cloud-node
And confuse this one
https://github.com/googleapis/nodejs-secret-manager/blob/master/samples/accessSecretVersion.js
with this one
https://github.com/googleapis/nodejs-secret-manager/blob/master/samples/getSecret.js
plus I made the mistake with the name as you pointed out
thank you very much for all your help!!

**Comment by rednebmas** [comment]
For people coming from a google search, this is what worked for me.

```javascript
import { SecretManagerServiceClient } from '@google-cloud/secret-manager';
const client = new SecretManagerServiceClient({
	keyFilename: 'path to secret key.json',
	projectId: 'myProjectID'
});

const [secret] = await client.accessSecretVersion({
	name: `projects/myProjectID/secrets/mySecretName/versions/latest`,
});

if (secret.payload && secret.payload.data) {
	const responsePayload = secret.payload.data.toString();
	console.info(`Payload: ${responsePayload}`);
}
```

**Comment by arnaud-cortisse** [comment]
And FYI, you can retrieve the "Resource ID" (that you needto retrieve a secret) in the web interface:
![image](https://user-images.githubusercontent.com/28689103/81038553-b58f3c80-8ea6-11ea-9a6f-327bf45098a5.png)

**Comment by garyo** [comment]
I just hit this same error and this issue helps me fix it. I have to say that the error message is not really helpful in this case. I bet it would help future users if you reject secret names without enough slash characters in them with a better error, like "secret names must contain the full path to the secret, e.g. /projects/*/secrets/*/versions/latest".

**Comment by yan-michael** [comment]
> I have to say that the error message is not really helpful in this case

Very key point – it seems to be just a default error message that speaks nothing about the root of the problem. In my case, it was that my environment variable containing the project ID was not being properly injected.

**Comment by ollydixon** [comment]
How do we get the resource id for multiple projects automatically?

**Comment by smakinson** [comment]
Incase this helps someone out, I ran in to this and this thread caused me to realize I had one of my `.env.project` files named wrong, so I was missing that portion of the path. The error message sent me in the wrong direction at first. That was fun  :)
